// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chunkMsg.proto

#include "chunkMsg.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace VFproto {
constexpr ChunkMsg::ChunkMsg(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : blockarr_(){}
struct ChunkMsgDefaultTypeInternal {
  constexpr ChunkMsgDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ChunkMsgDefaultTypeInternal() {}
  union {
    ChunkMsg _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ChunkMsgDefaultTypeInternal _ChunkMsg_default_instance_;
}  // namespace VFproto
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_chunkMsg_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_chunkMsg_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_chunkMsg_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_chunkMsg_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::VFproto::ChunkMsg, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::VFproto::ChunkMsg, blockarr_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::VFproto::ChunkMsg)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::VFproto::_ChunkMsg_default_instance_),
};

const char descriptor_table_protodef_chunkMsg_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016chunkMsg.proto\022\007VFproto\"\034\n\010ChunkMsg\022\020\n"
  "\010blockArr\030\001 \003(\005"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_chunkMsg_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chunkMsg_2eproto = {
  false, false, 55, descriptor_table_protodef_chunkMsg_2eproto, "chunkMsg.proto", 
  &descriptor_table_chunkMsg_2eproto_once, nullptr, 0, 1,
  schemas, file_default_instances, TableStruct_chunkMsg_2eproto::offsets,
  file_level_metadata_chunkMsg_2eproto, file_level_enum_descriptors_chunkMsg_2eproto, file_level_service_descriptors_chunkMsg_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_chunkMsg_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_chunkMsg_2eproto);
  return descriptor_table_chunkMsg_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_chunkMsg_2eproto(&descriptor_table_chunkMsg_2eproto);
namespace VFproto {

// ===================================================================

class ChunkMsg::_Internal {
 public:
};

ChunkMsg::ChunkMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  blockarr_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:VFproto.ChunkMsg)
}
ChunkMsg::ChunkMsg(const ChunkMsg& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      blockarr_(from.blockarr_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:VFproto.ChunkMsg)
}

void ChunkMsg::SharedCtor() {
}

ChunkMsg::~ChunkMsg() {
  // @@protoc_insertion_point(destructor:VFproto.ChunkMsg)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void ChunkMsg::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void ChunkMsg::ArenaDtor(void* object) {
  ChunkMsg* _this = reinterpret_cast< ChunkMsg* >(object);
  (void)_this;
}
void ChunkMsg::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ChunkMsg::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ChunkMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:VFproto.ChunkMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  blockarr_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ChunkMsg::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // repeated int32 blockArr = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          ptr -= 1;
          do {
            ptr += 1;
            _internal_add_blockarr(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<8>(ptr));
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedInt32Parser(_internal_mutable_blockarr(), ptr, ctx);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ChunkMsg::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:VFproto.ChunkMsg)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 blockArr = 1;
  for (int i = 0, n = this->_internal_blockarr_size(); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_blockarr(i), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:VFproto.ChunkMsg)
  return target;
}

size_t ChunkMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:VFproto.ChunkMsg)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 blockArr = 1;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      Int32Size(this->blockarr_);
    total_size += 1 *
                  ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_blockarr_size());
    total_size += data_size;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ChunkMsg::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:VFproto.ChunkMsg)
  GOOGLE_DCHECK_NE(&from, this);
  const ChunkMsg* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<ChunkMsg>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:VFproto.ChunkMsg)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:VFproto.ChunkMsg)
    MergeFrom(*source);
  }
}

void ChunkMsg::MergeFrom(const ChunkMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:VFproto.ChunkMsg)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  blockarr_.MergeFrom(from.blockarr_);
}

void ChunkMsg::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:VFproto.ChunkMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChunkMsg::CopyFrom(const ChunkMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:VFproto.ChunkMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChunkMsg::IsInitialized() const {
  return true;
}

void ChunkMsg::InternalSwap(ChunkMsg* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  blockarr_.InternalSwap(&other->blockarr_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ChunkMsg::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace VFproto
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::VFproto::ChunkMsg* Arena::CreateMaybeMessage< ::VFproto::ChunkMsg >(Arena* arena) {
  return Arena::CreateMessageInternal< ::VFproto::ChunkMsg >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
