// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chunkMsg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_chunkMsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_chunkMsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015005 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_chunkMsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_chunkMsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_chunkMsg_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_chunkMsg_2eproto_metadata_getter(int index);
namespace VFproto {
class ChunkMsg;
struct ChunkMsgDefaultTypeInternal;
extern ChunkMsgDefaultTypeInternal _ChunkMsg_default_instance_;
}  // namespace VFproto
PROTOBUF_NAMESPACE_OPEN
template<> ::VFproto::ChunkMsg* Arena::CreateMaybeMessage<::VFproto::ChunkMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace VFproto {

// ===================================================================

class ChunkMsg PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VFproto.ChunkMsg) */ {
 public:
  inline ChunkMsg() : ChunkMsg(nullptr) {}
  virtual ~ChunkMsg();
  explicit constexpr ChunkMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ChunkMsg(const ChunkMsg& from);
  ChunkMsg(ChunkMsg&& from) noexcept
    : ChunkMsg() {
    *this = ::std::move(from);
  }

  inline ChunkMsg& operator=(const ChunkMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ChunkMsg& operator=(ChunkMsg&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ChunkMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const ChunkMsg* internal_default_instance() {
    return reinterpret_cast<const ChunkMsg*>(
               &_ChunkMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ChunkMsg& a, ChunkMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(ChunkMsg* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ChunkMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ChunkMsg* New() const final {
    return CreateMaybeMessage<ChunkMsg>(nullptr);
  }

  ChunkMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ChunkMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ChunkMsg& from);
  void MergeFrom(const ChunkMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ChunkMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VFproto.ChunkMsg";
  }
  protected:
  explicit ChunkMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_chunkMsg_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBlockArrFieldNumber = 1,
  };
  // repeated int32 blockArr = 1;
  int blockarr_size() const;
  private:
  int _internal_blockarr_size() const;
  public:
  void clear_blockarr();
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_blockarr(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      _internal_blockarr() const;
  void _internal_add_blockarr(::PROTOBUF_NAMESPACE_ID::int32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      _internal_mutable_blockarr();
  public:
  ::PROTOBUF_NAMESPACE_ID::int32 blockarr(int index) const;
  void set_blockarr(int index, ::PROTOBUF_NAMESPACE_ID::int32 value);
  void add_blockarr(::PROTOBUF_NAMESPACE_ID::int32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
      blockarr() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
      mutable_blockarr();

  // @@protoc_insertion_point(class_scope:VFproto.ChunkMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 > blockarr_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_chunkMsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ChunkMsg

// repeated int32 blockArr = 1;
inline int ChunkMsg::_internal_blockarr_size() const {
  return blockarr_.size();
}
inline int ChunkMsg::blockarr_size() const {
  return _internal_blockarr_size();
}
inline void ChunkMsg::clear_blockarr() {
  blockarr_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ChunkMsg::_internal_blockarr(int index) const {
  return blockarr_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ChunkMsg::blockarr(int index) const {
  // @@protoc_insertion_point(field_get:VFproto.ChunkMsg.blockArr)
  return _internal_blockarr(index);
}
inline void ChunkMsg::set_blockarr(int index, ::PROTOBUF_NAMESPACE_ID::int32 value) {
  blockarr_.Set(index, value);
  // @@protoc_insertion_point(field_set:VFproto.ChunkMsg.blockArr)
}
inline void ChunkMsg::_internal_add_blockarr(::PROTOBUF_NAMESPACE_ID::int32 value) {
  blockarr_.Add(value);
}
inline void ChunkMsg::add_blockarr(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_add_blockarr(value);
  // @@protoc_insertion_point(field_add:VFproto.ChunkMsg.blockArr)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
ChunkMsg::_internal_blockarr() const {
  return blockarr_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >&
ChunkMsg::blockarr() const {
  // @@protoc_insertion_point(field_list:VFproto.ChunkMsg.blockArr)
  return _internal_blockarr();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
ChunkMsg::_internal_mutable_blockarr() {
  return &blockarr_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::int32 >*
ChunkMsg::mutable_blockarr() {
  // @@protoc_insertion_point(field_mutable_list:VFproto.ChunkMsg.blockArr)
  return _internal_mutable_blockarr();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace VFproto

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_chunkMsg_2eproto
