#pragma once

// /**
//  * M_ represent the macros
// */

// /*! @defgroup buttons Mouse buttons
//  *  @brief Mouse button IDs.
//  *
//  *  See [mouse button input](@ref input_mouse_button) for how these are used.
//  *
//  *  @ingroup input
//  *  @{ */
// #define M_Input_MOUSE_BUTTON_1 0
// #define M_Input_MOUSE_BUTTON_2 1
// #define M_Input_MOUSE_BUTTON_3 2
// #define M_Input_MOUSE_BUTTON_4 3
// #define M_Input_MOUSE_BUTTON_5 4
// #define M_Input_MOUSE_BUTTON_6 5
// #define M_Input_MOUSE_BUTTON_7 6
// #define M_Input_MOUSE_BUTTON_8 7
// #define M_Input_MOUSE_BUTTON_LAST M_Input_MOUSE_BUTTON_8
// #define M_Input_MOUSE_BUTTON_LEFT M_Input_MOUSE_BUTTON_1
// #define M_Input_MOUSE_BUTTON_RIGHT M_Input_MOUSE_BUTTON_2
// #define M_Input_MOUSE_BUTTON_MIDDLE M_Input_MOUSE_BUTTON_3
// /*! @} */

// /* The unknown key */
// #define M_Input_KEY_UNKNOWN -1

// /* Printable keys */
// #define M_Input_KEY_SPACE 32
// #define M_Input_KEY_APOSTROPHE 39 /* ' */
// #define M_Input_KEY_COMMA 44      /*  */
// #define M_Input_KEY_MINUS 45      /* - */
// #define M_Input_KEY_PERIOD 46     /* . */
// #define M_Input_KEY_SLASH 47      /* / */
// #define M_Input_KEY_0 48
// #define M_Input_KEY_1 49
// #define M_Input_KEY_2 50
// #define M_Input_KEY_3 51
// #define M_Input_KEY_4 52
// #define M_Input_KEY_5 53
// #define M_Input_KEY_6 54
// #define M_Input_KEY_7 55
// #define M_Input_KEY_8 56
// #define M_Input_KEY_9 57
// #define M_Input_KEY_SEMICOLON 59 /* ; */
// #define M_Input_KEY_EQUAL 61     /*  */
// #define M_Input_KEY_A 65
// #define M_Input_KEY_B 66
// #define M_Input_KEY_C 67
// #define M_Input_KEY_D 68
// #define M_Input_KEY_E 69
// #define M_Input_KEY_F 70
// #define M_Input_KEY_G 71
// #define M_Input_KEY_H 72
// #define M_Input_KEY_I 73
// #define M_Input_KEY_J 74
// #define M_Input_KEY_K 75
// #define M_Input_KEY_L 76
// #define M_Input_KEY_M 77
// #define M_Input_KEY_N 78
// #define M_Input_KEY_O 79
// #define M_Input_KEY_P 80
// #define M_Input_KEY_Q 81
// #define M_Input_KEY_R 82
// #define M_Input_KEY_S 83
// #define M_Input_KEY_T 84
// #define M_Input_KEY_U 85
// #define M_Input_KEY_V 86
// #define M_Input_KEY_W 87
// #define M_Input_KEY_X 88
// #define M_Input_KEY_Y 89
// #define M_Input_KEY_Z 90
// #define M_Input_KEY_LEFT_BRACKET 91  /* [ */
// #define M_Input_KEY_BACKSLASH 92     /* \ */
// #define M_Input_KEY_RIGHT_BRACKET 93 /* ] */
// #define M_Input_KEY_GRAVE_ACCENT 96  /* ` */
// #define M_Input_KEY_WORLD_1 161      /* non-US #1 */
// #define M_Input_KEY_WORLD_2 162      /* non-US #2 */

// /* Function keys */
// #define M_Input_KEY_ESCAPE 256
// #define M_Input_KEY_ENTER 257
// #define M_Input_KEY_TAB 258
// #define M_Input_KEY_BACKSPACE 259
// #define M_Input_KEY_INSERT 260
// #define M_Input_KEY_DELETE 261
// #define M_Input_KEY_RIGHT 262
// #define M_Input_KEY_LEFT 263
// #define M_Input_KEY_DOWN 264
// #define M_Input_KEY_UP 265
// #define M_Input_KEY_PAGE_UP 266
// #define M_Input_KEY_PAGE_DOWN 267
// #define M_Input_KEY_HOME 268
// #define M_Input_KEY_END 269
// #define M_Input_KEY_CAPS_LOCK 280
// #define M_Input_KEY_SCROLL_LOCK 281
// #define M_Input_KEY_NUM_LOCK 282
// #define M_Input_KEY_PRINT_SCREEN 283
// #define M_Input_KEY_PAUSE 284
// #define M_Input_KEY_F1 290
// #define M_Input_KEY_F2 291
// #define M_Input_KEY_F3 292
// #define M_Input_KEY_F4 293
// #define M_Input_KEY_F5 294
// #define M_Input_KEY_F6 295
// #define M_Input_KEY_F7 296
// #define M_Input_KEY_F8 297
// #define M_Input_KEY_F9 298
// #define M_Input_KEY_F10 299
// #define M_Input_KEY_F11 300
// #define M_Input_KEY_F12 301
// #define M_Input_KEY_F13 302
// #define M_Input_KEY_F14 303
// #define M_Input_KEY_F15 304
// #define M_Input_KEY_F16 305
// #define M_Input_KEY_F17 306
// #define M_Input_KEY_F18 307
// #define M_Input_KEY_F19 308
// #define M_Input_KEY_F20 309
// #define M_Input_KEY_F21 310
// #define M_Input_KEY_F22 311
// #define M_Input_KEY_F23 312
// #define M_Input_KEY_F24 313
// #define M_Input_KEY_F25 314
// #define M_Input_KEY_KP_0 320
// #define M_Input_KEY_KP_1 321
// #define M_Input_KEY_KP_2 322
// #define M_Input_KEY_KP_3 323
// #define M_Input_KEY_KP_4 324
// #define M_Input_KEY_KP_5 325
// #define M_Input_KEY_KP_6 326
// #define M_Input_KEY_KP_7 327
// #define M_Input_KEY_KP_8 328
// #define M_Input_KEY_KP_9 329
// #define M_Input_KEY_KP_DECIMAL 330
// #define M_Input_KEY_KP_DIVIDE 331
// #define M_Input_KEY_KP_MULTIPLY 332
// #define M_Input_KEY_KP_SUBTRACT 333
// #define M_Input_KEY_KP_ADD 334
// #define M_Input_KEY_KP_ENTER 335
// #define M_Input_KEY_KP_EQUAL 336
// #define M_Input_KEY_LEFT_SHIFT 340
// #define M_Input_KEY_LEFT_CONTROL 341
// #define M_Input_KEY_LEFT_ALT 342
// #define M_Input_KEY_LEFT_SUPER 343
// #define M_Input_KEY_RIGHT_SHIFT 344
// #define M_Input_KEY_RIGHT_CONTROL 345
// #define M_Input_KEY_RIGHT_ALT 346
// #define M_Input_KEY_RIGHT_SUPER 347
// #define M_Input_KEY_MENU 348

#define M_Input_KEY_UNKNOWN 0

#define M_Input_KEY_RETURN '\r'
#define M_Input_KEY_ESCAPE '\033'
#define M_Input_KEY_BACKSPACE '\b'
#define M_Input_KEY_TAB '\t'
#define M_Input_KEY_SPACE ' '
#define M_Input_KEY_EXCLAIM '!'
#define M_Input_KEY_QUOTEDBL '"'
#define M_Input_KEY_HASH '#'
#define M_Input_KEY_PERCENT '%'
#define M_Input_KEY_DOLLAR '$'
#define M_Input_KEY_AMPERSAND '&'
#define M_Input_KEY_QUOTE '\''
#define M_Input_KEY_LEFTPAREN '('
#define M_Input_KEY_RIGHTPAREN ')'
#define M_Input_KEY_ASTERISK '*'
#define M_Input_KEY_PLUS '+'
#define M_Input_KEY_COMMA  ''
#define M_Input_KEY_MINUS '-'
#define M_Input_KEY_PERIOD '.'
#define M_Input_KEY_SLASH '/'
#define M_Input_KEY_0 '0'
#define M_Input_KEY_1 '1'
#define M_Input_KEY_2 '2'
#define M_Input_KEY_3 '3'
#define M_Input_KEY_4 '4'
#define M_Input_KEY_5 '5'
#define M_Input_KEY_6 '6'
#define M_Input_KEY_7 '7'
#define M_Input_KEY_8 '8'
#define M_Input_KEY_9 '9'
#define M_Input_KEY_COLON ':'
#define M_Input_KEY_SEMICOLON ';'
#define M_Input_KEY_LESS '<'
#define M_Input_KEY_EQUALS  ''
#define M_Input_KEY_GREATER '>'
#define M_Input_KEY_QUESTION '?'
#define M_Input_KEY_AT '@'

/*
       Skip uppercase letters
     */

#define M_Input_KEY_LEFTBRACKET '['
#define M_Input_KEY_BACKSLASH '\\'
#define M_Input_KEY_RIGHTBRACKET ']'
#define M_Input_KEY_CARET '^'
#define M_Input_KEY_UNDERSCORE '_'
#define M_Input_KEY_BACKQUOTE '`'
#define M_Input_KEY_A 'a'
#define M_Input_KEY_B 'b'
#define M_Input_KEY_C 'c'
#define M_Input_KEY_D 'd'
#define M_Input_KEY_E 'e'
#define M_Input_KEY_F 'f'
#define M_Input_KEY_G 'g'
#define M_Input_KEY_H 'h'
#define M_Input_KEY_I 'i'
#define M_Input_KEY_J 'j'
#define M_Input_KEY_K 'k'
#define M_Input_KEY_L 'l'
#define M_Input_KEY_M 'm'
#define M_Input_KEY_N 'n'
#define M_Input_KEY_O 'o'
#define M_Input_KEY_P 'p'
#define M_Input_KEY_Q 'q'
#define M_Input_KEY_R 'r'
#define M_Input_KEY_S 's'
#define M_Input_KEY_T 't'
#define M_Input_KEY_U 'u'
#define M_Input_KEY_V 'v'
#define M_Input_KEY_W 'w'
#define M_Input_KEY_X 'x'
#define M_Input_KEY_Y 'y'
#define M_Input_KEY_Z 'z'

#define M_Input_KEY_CAPSLOCK SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK)

#define M_Input_KEY_F1 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1)
#define M_Input_KEY_F2 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2)
#define M_Input_KEY_F3 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3)
#define M_Input_KEY_F4 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4)
#define M_Input_KEY_F5 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5)
#define M_Input_KEY_F6 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6)
#define M_Input_KEY_F7 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7)
#define M_Input_KEY_F8 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8)
#define M_Input_KEY_F9 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9)
#define M_Input_KEY_F10 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10)
#define M_Input_KEY_F11 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11)
#define M_Input_KEY_F12 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12)

#define M_Input_KEY_PRINTSCREEN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN)
#define M_Input_KEY_SCROLLLOCK SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK)
#define M_Input_KEY_PAUSE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE)
#define M_Input_KEY_INSERT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT)
#define M_Input_KEY_HOME SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME)
#define M_Input_KEY_PAGEUP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP)
#define M_Input_KEY_DELETE '\177'
#define M_Input_KEY_END SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END)
#define M_Input_KEY_PAGEDOWN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN)
#define M_Input_KEY_RIGHT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT)
#define M_Input_KEY_LEFT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT)
#define M_Input_KEY_DOWN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN)
#define M_Input_KEY_UP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP)

#define M_Input_KEY_NUMLOCKCLEAR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR)
#define M_Input_KEY_KP_DIVIDE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE)
#define M_Input_KEY_KP_MULTIPLY SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY)
#define M_Input_KEY_KP_MINUS SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS)
#define M_Input_KEY_KP_PLUS SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS)
#define M_Input_KEY_KP_ENTER SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER)
#define M_Input_KEY_KP_1 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1)
#define M_Input_KEY_KP_2 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2)
#define M_Input_KEY_KP_3 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3)
#define M_Input_KEY_KP_4 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4)
#define M_Input_KEY_KP_5 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5)
#define M_Input_KEY_KP_6 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6)
#define M_Input_KEY_KP_7 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7)
#define M_Input_KEY_KP_8 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8)
#define M_Input_KEY_KP_9 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9)
#define M_Input_KEY_KP_0 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0)
#define M_Input_KEY_KP_PERIOD SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD)

#define M_Input_KEY_APPLICATION SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION)
#define M_Input_KEY_POWER SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER)
#define M_Input_KEY_KP_EQUALS SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS)
#define M_Input_KEY_F13 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13)
#define M_Input_KEY_F14 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14)
#define M_Input_KEY_F15 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15)
#define M_Input_KEY_F16 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16)
#define M_Input_KEY_F17 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17)
#define M_Input_KEY_F18 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18)
#define M_Input_KEY_F19 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19)
#define M_Input_KEY_F20 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20)
#define M_Input_KEY_F21 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21)
#define M_Input_KEY_F22 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22)
#define M_Input_KEY_F23 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23)
#define M_Input_KEY_F24 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24)
#define M_Input_KEY_EXECUTE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE)
#define M_Input_KEY_HELP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP)
#define M_Input_KEY_MENU SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU)
#define M_Input_KEY_SELECT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT)
#define M_Input_KEY_STOP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP)
#define M_Input_KEY_AGAIN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN)
#define M_Input_KEY_UNDO SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO)
#define M_Input_KEY_CUT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT)
#define M_Input_KEY_COPY SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY)
#define M_Input_KEY_PASTE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE)
#define M_Input_KEY_FIND SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND)
#define M_Input_KEY_MUTE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE)
#define M_Input_KEY_VOLUMEUP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP)
#define M_Input_KEY_VOLUMEDOWN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN)
#define M_Input_KEY_KP_COMMA SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA)
#define M_Input_KEY_KP_EQUALSAS400 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)

#define M_Input_KEY_ALTERASE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE)
#define M_Input_KEY_SYSREQ SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ)
#define M_Input_KEY_CANCEL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL)
#define M_Input_KEY_CLEAR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR)
#define M_Input_KEY_PRIOR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR)
#define M_Input_KEY_RETURN2 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2)
#define M_Input_KEY_SEPARATOR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR)
#define M_Input_KEY_OUT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT)
#define M_Input_KEY_OPER SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER)
#define M_Input_KEY_CLEARAGAIN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN)
#define M_Input_KEY_CRSEL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL)
#define M_Input_KEY_EXSEL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL)

#define M_Input_KEY_KP_00 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00)
#define M_Input_KEY_KP_000 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000)
#define M_Input_KEY_THOUSANDSSEPARATOR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)
#define M_Input_KEY_DECIMALSEPARATOR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)
#define M_Input_KEY_CURRENCYUNIT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT)
#define M_Input_KEY_CURRENCYSUBUNIT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)
#define M_Input_KEY_KP_LEFTPAREN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN)
#define M_Input_KEY_KP_RIGHTPAREN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN)
#define M_Input_KEY_KP_LEFTBRACE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE)
#define M_Input_KEY_KP_RIGHTBRACE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE)
#define M_Input_KEY_KP_TAB SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB)
#define M_Input_KEY_KP_BACKSPACE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE)
#define M_Input_KEY_KP_A SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A)
#define M_Input_KEY_KP_B SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B)
#define M_Input_KEY_KP_C SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C)
#define M_Input_KEY_KP_D SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D)
#define M_Input_KEY_KP_E SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E)
#define M_Input_KEY_KP_F SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F)
#define M_Input_KEY_KP_XOR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR)
#define M_Input_KEY_KP_POWER SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER)
#define M_Input_KEY_KP_PERCENT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT)
#define M_Input_KEY_KP_LESS SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS)
#define M_Input_KEY_KP_GREATER SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER)
#define M_Input_KEY_KP_AMPERSAND SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND)
#define M_Input_KEY_KP_DBLAMPERSAND SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLAMPERSAND)
#define M_Input_KEY_KP_VERTICALBAR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)
#define M_Input_KEY_KP_DBLVERTICALBAR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DBLVERTICALBAR)
#define M_Input_KEY_KP_COLON SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON)
#define M_Input_KEY_KP_HASH SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH)
#define M_Input_KEY_KP_SPACE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE)
#define M_Input_KEY_KP_AT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT)
#define M_Input_KEY_KP_EXCLAM SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM)
#define M_Input_KEY_KP_MEMSTORE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE)
#define M_Input_KEY_KP_MEMRECALL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL)
#define M_Input_KEY_KP_MEMCLEAR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR)
#define M_Input_KEY_KP_MEMADD SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD)
#define M_Input_KEY_KP_MEMSUBTRACT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)
#define M_Input_KEY_KP_MEMMULTIPLY SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)
#define M_Input_KEY_KP_MEMDIVIDE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE)
#define M_Input_KEY_KP_PLUSMINUS SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS)
#define M_Input_KEY_KP_CLEAR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR)
#define M_Input_KEY_KP_CLEARENTRY SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY)
#define M_Input_KEY_KP_BINARY SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY)
#define M_Input_KEY_KP_OCTAL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL)
#define M_Input_KEY_KP_DECIMAL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL)
#define M_Input_KEY_KP_HEXADECIMAL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)

#define M_Input_KEY_LCTRL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL)
#define M_Input_KEY_LSHIFT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT)
#define M_Input_KEY_LALT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT)
#define M_Input_KEY_LGUI SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI)
#define M_Input_KEY_RCTRL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL)
#define M_Input_KEY_RSHIFT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT)
#define M_Input_KEY_RALT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT)
#define M_Input_KEY_RGUI SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI)

#define M_Input_KEY_MODE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE)

#define M_Input_KEY_AUDIONEXT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIONEXT)
#define M_Input_KEY_AUDIOPREV SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPREV)
#define M_Input_KEY_AUDIOSTOP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOSTOP)
#define M_Input_KEY_AUDIOPLAY SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOPLAY)
#define M_Input_KEY_AUDIOMUTE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOMUTE)
#define M_Input_KEY_MEDIASELECT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIASELECT)
#define M_Input_KEY_WWW SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WWW)
#define M_Input_KEY_MAIL SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MAIL)
#define M_Input_KEY_CALCULATOR SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALCULATOR)
#define M_Input_KEY_COMPUTER SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COMPUTER)
#define M_Input_KEY_AC_SEARCH SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH)
#define M_Input_KEY_AC_HOME SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME)
#define M_Input_KEY_AC_BACK SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK)
#define M_Input_KEY_AC_FORWARD SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD)
#define M_Input_KEY_AC_STOP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP)
#define M_Input_KEY_AC_REFRESH SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH)
#define M_Input_KEY_AC_BOOKMARKS SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS)

#define M_Input_KEY_BRIGHTNESSDOWN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSDOWN)
#define M_Input_KEY_BRIGHTNESSUP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_BRIGHTNESSUP)
#define M_Input_KEY_DISPLAYSWITCH SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DISPLAYSWITCH)
#define M_Input_KEY_KBDILLUMTOGGLE SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMTOGGLE)
#define M_Input_KEY_KBDILLUMDOWN SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMDOWN)
#define M_Input_KEY_KBDILLUMUP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KBDILLUMUP)
#define M_Input_KEY_EJECT SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EJECT)
#define M_Input_KEY_SLEEP SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP)
#define M_Input_KEY_APP1 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP1)
#define M_Input_KEY_APP2 SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APP2)

#define M_Input_KEY_AUDIOREWIND SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOREWIND)
#define M_Input_KEY_AUDIOFASTFORWARD SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AUDIOFASTFORWARD)